# Generated by Django 3.1 on 2020-09-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20200916_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='img',
            field=models.ImageField(default='no-image.png', upload_to='skill_image'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='img',
            field=models.ImageField(default='no-image.png', upload_to='skill_image'),
        ),
    ]
