# Generated by Django 3.1 on 2020-09-16 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20200916_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoints',
            name='owner',
        ),
        migrations.AddField(
            model_name='skill',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='prepared_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.userskills', verbose_name='Изученный скилл'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.IntegerField(null=True, verbose_name='Уровень скилла'),
        ),
    ]
