# Generated by Django 3.1 on 2020-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20200917_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskills',
            name='level',
            field=models.IntegerField(null=True, verbose_name='Уровень скилла'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cost',
            field=models.IntegerField(null=True, verbose_name='Стоимость'),
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
