# Generated by Django 3.1 on 2020-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_skill_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskills',
            name='damage',
            field=models.IntegerField(null=True),
        ),
    ]
