# Generated by Django 3.1 on 2020-09-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_userskills_damage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='skill_image', verbose_name='Ветка скиллов')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='element',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
