# Generated by Django 3.1 on 2020-09-19 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_auto_20200919_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importer',
            name='file',
            field=models.FilePathField(path='pictures/skill_image/'),
        ),
        migrations.CreateModel(
            name='HelperImporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='skill_image')),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.importer')),
            ],
        ),
    ]
