# Generated by Django 3.1 on 2020-09-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_helperexporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelperExporter',
        ),
    ]
